
export const PRODUCT_LIST_REQUEST ="RODUCT_LIST_REQUEST";
export const PRODUCT_LIST_SUCCESS ="RODUCT_LIST_SUCCESS";
export const PRODUCT_LIST_FAIL ="RODUCT_LIST_FAIL";

export const PRODUCT_DETAIL_REQUEST ="RODUCT_DETAIL_REQUEST";
export const PRODUCT_DETAIL_SUCCESS ="RODUCT_DETAIL_SUCCESS";
export const PRODUCT_DETAIL_FAIL ="RODUCT_DETAIL_FAIL";


